export const FETCH_CHARACTER_LIST = "FETCH_CHARACTER_LIST";
export const FETCH_CHARACTER_LIST_SUCCESS = "FETCH_CHARACTER_LIST_SUCCESS";
export const FETCH_CHARACTER_LIST_FAILED = "FETCH_CHARACTER_LIST_FAILED";

export const HIDE_ALERT = "HIDE_ALERT";
